name: FireWorks
version: 2.0
descriptin:
api-version: 1.13
authors: [68mutuba,Toto31010]
website: https://twitter.com/68mutuba_2
main: io.github.mutuba.fireworks.Main

commands:
  fw:
    permission: fireworks.*
    description: FireWorks Generate Command.
    permission-message: Unknown command. Type "/help" for help.
